### ISSUE TITLE
Error on startup:  ModuleNotFoundError: No module named 'biwenger'

### ISSUE THREAD

**Issue by CarlosLopezES** [Poppeyye/biwenger_bot#9]
Hi,

First of all, thanks a lot for this project. I'm trying to execute in docker, and I've this issue on the app.py launch:

` ModuleNotFoundError: No module named 'biwenger'`

Any advises? Thanks a lot.

**Comment by Poppeyye** [comment]
Hola Carlos qué tal?

Te contesto en español que yo creo que toda la comunidad de biwenger somos de habla hispana prácticamente. 
Gracias por pasarte por aquí e intentar jugar con el proyecto.

La verdad que llevaba bastante tiempo sin meterme y gracias a tu comentario me he vuelto a clonar el proyecto a ver si seguía funcionando, y para mi sorpresa, sí 👍 .

La verdad que no he probado a ejecutarlo con docker, pero al ser un proyecto tan sencillo entiendo que has podido configurar mal el dockerfile? te recomiendo que sigas alguna guía de este tipo https://community.render.com/t/docker-module-not-found/12872.

Es posible que no hayas copiado bien los modulos o no hayas configurado bien el working dir.

Yo para ejecutarlo uso virtualenv, configuro las variables de entorno necesarias y ejecuto python app.py.

Por otro lado, es probable que al estar aún fuera de temporada encuentres algún fallo de ejecución (divisiones por cero al no disponer de datos de los jugadores todavía)

Si consigues hacerlo funcionar con docker te animo a que hagas una PR, así como si te apetece modificar cualquier parte del código o clonarlo a tu gusto, adelante.

Lo hice por diversión y por si alguien tenía ideas similares que se basara un poco en algunas de las cosas que se hacen aquí.

Saludos!

**Comment by Poppeyye** [comment]
> Hi,
> 
> First of all, thanks a lot for this project. I'm trying to execute in docker, and I've this issue on the app.py launch:
> 
> ` ModuleNotFoundError: No module named 'biwenger'`
> 
> Any advises? Thanks a lot.

**Comment by CarlosLopezES** [comment]
¡Hola!

Muchas gracias por tu respuesta. Ya me di cuenta del fallo, era una variable de entorno, y con eso ya se ejecuta correctamente. Ahora mismo tras ejecutarse hay un error de índices, seguramente justo lo que comentabas:

```
bot_1  | Traceback (most recent call last):
bot_1  |   File "/codebase/telegram_client/app.py", line 62, in <module>
bot_1  |     asyncio.run(main())  # startpoint
bot_1  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
bot_1  |     return loop.run_until_complete(main)
bot_1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
bot_1  |     return future.result()
bot_1  |   File "/codebase/telegram_client/app.py", line 32, in main
bot_1  |     plys_user = MarketNotice().show(biwenger.get_players_in_market(free=False))
bot_1  |   File "/codebase/biwenger/league_logic.py", line 84, in get_players_in_market
bot_1  |     offer.update(self.get_player_extended_information(str(p)))
bot_1  |   File "/codebase/biwenger/league_logic.py", line 216, in get_player_extended_information
bot_1  |     raw_stats = self.raw_stats_analysis(info_format['reports'])
bot_1  |   File "/codebase/biwenger/league_logic.py", line 197, in raw_stats_analysis
bot_1  |     per_min_played = "{:.2f}".format(total_minutes_played / absolute_minutes)
bot_1  | ZeroDivisionError: division by zero

```

A ver en un ratín que comienza la competición si queda solventado. Y sí por supuesto, si lo consigo ejecutar correctamente en Docker, comparto el código al proyecto :)

Un saludo,

**Comment by lageleage** [comment]
Me pasaba lo mismo que a Carlos, me alegro de que quedara arreglado con la última modificación.

Lo que hice en mi caso fue situar la carpeta biwenger dentro de la de telegram_client para que al ejecutar app.py encontrara el módulo "biwenger". Seguramente sea tema de mala configuración por mi parte, pero así funcionaba. Estuve trasteándolo y efectivamente da error por división entre cero, pero se puede aplicar un parche temporalmente para anular ese error mientras empieza la liga y no.

Si alguien se anima a hacer un script que recoja los datos de los movimientos del día y los inserte en una base de datos, sabiendo el valor de equipo inicial el primer día de competición se puede saber qué dinero tienen nuestros rivales y por ende, su puja máxima. Yo hice un algoritmo muy sencillito hace años para ello pero tenías que meter a mano todos los movimientos, lo cual lleva mucho tiempo. Por falta de tiempo no lo he automatizado, si alguien une ambas cosas tenemos herramienta para rato.

Un saludo y gracias por la funcionalidad, muy útil!

**Comment by Poppeyye** [comment]
Me alegro de que hayas encontrado el error,

Es cierto que en el main me falta añadir esa variable de entorno como obligatoria. Lo apunto para actualizarlo.

Lo que comentas @alvarillolag jajaj, obviamente se puede hacer, pero la verdad que decidí no hacerlo para no joder a mis amigos, que juego con ellos y apostamos dinero xD. Pensé en hacer otras cosas algo más difíciles como estimar el precio de puja de un jugador con un % de seguridad con el que te lo llevarías. P.e, puja 4.3M por tal y te lo llevas al 85%.

A ver cuando empiece la liga qué cosas nuevas hay y si se sigue sosteniendo el mismo modelo de datos, que al no ser oficial puede haber cambios. Todos las urls las cogí directamente de inspeccionar la web y los "GETS" que se hacían al pulsar cada botón de la app.

Tened en cuenta también que el código funciona para una configuración concreta de la versión premium y también los mensajes que se envían a telegram son muy personalizados para mi liga. Quizás falte soporte para algunos tipos de movimientos como cesiones y tal

**Comment by HariTrigger** [comment]
No seria más fácil tener un main.py en el root del proyecto @Poppeyye?
